site_name: Datto.DBPool.Refresh
site_url: https://datto-dbpool-refresh.kentsapp.com/
site_description: PowerShell module is used to refresh all child containers in Datto (Kaseya) DBPool
site_dir: ./site/
docs_dir: ./docs/site/
exclude_docs: |
  /en-US/
  /generated/
repo_url: https://github.com/cksapp/Datto-DBPool_Refresh
theme:
  name: material
  #logo: assets/logo.svg
  #favicon: assets/favicon.ico

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Toggle light/dark mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: blue
      accent: deep orange
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      primary: indigo
      accent: deep purple

  icon:
    repo: material/github
  features:
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    #- navigation.footer # Add page navigation to the footer
    - navigation.tabs
    #- navigation.tabs.sticky # Keep the tabs visible when scrolling
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow # Highlight the current section in the table of contents
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cksapp
      name: GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kentsapp
      name: LinkedIn

copyright: Copyright &copy; 2023 - 2024 Kent Sapp
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      permalink: ðŸ”—
plugins:
  - privacy
  - search
  - social
  - open-in-new-tab
  - glightbox
